version: '3.8'

services:
  addautodevice-app:
    build: .
    image: addautodevice-app
    volumes:
      - /data/livenx-server/data/log:/data/livenx-server/data/log  # Mount the log directory from the host to the container
    environment:
      - LIVENX_API_HOST=0.0.0.0
      - LIVENX_API_PORT=8093
      - LIVENX_API_TOKEN=""
      - LIVENX_TARGET_IP=""
    working_dir: /usr/src/app
